#!/bin/bash

set -e

if ratos-pkg-missing-yay "$@"; then
    yay -S --noconfirm "$@" || exit 1
fi

for pkg in "$@"; do
    if ! yay -Q "$pkg" &>/dev/null; then
        echo -e "\033[31mError: Package '$pkg' did not install\033[0m" >&2
        exit 1
    fi
done

exit 0