#!/bin/bash

if (($# == 0)); then
  echo "Usage: ratos-launch-or-focus-webapp [window-pattern] [url-and-flags...]"
  exit 1
fi

WINDOW_PATTERN="$1"
shift
LAUNCH_COMMAND="ratos-launch-webapp $@"

exec ratos-launch-or-focus "$WINDOW_PATTERN" "$LAUNCH_COMMAND"